version: '3'

services:
  postgres-compose:
    image: postgres
    environment:
      POSTGRES_DB: fast-food-produto
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: "Postgres2023!"
      PGDATA: /data/postgres
    ports:
      - "5432:5432"
    volumes:
      - postgres:/data/postgres
    networks:
      - postgres-network

  pgadmin-compose:
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: "fast-food@gmail.com"
      PGADMIN_DEFAULT_PASSWORD: "PgAdmin2023!"
    ports:
      - "15432:80"
    depends_on:
      - postgres-compose
    networks:
      - postgres-network

  fast-food:
    build: .
    ports:
      - "8094:8080"
    environment:
      JAVA_OPTS: -Ddatabase_url=postgres-compose -Ddatabase_user=postgres -Ddatabase_password=Postgres2023! -Database_name=fast-food-produto
    networks:
      - postgres-network
    depends_on:
      - postgres-compose

networks:
  postgres-network:
    driver: bridge

volumes:
  postgres: